import { type DynamicScheme, MaterialDynamicColors } from "@material/material-color-utilities";
import { type SerializedScheme, colors } from "./utils";

/**
 * @description Serializes the {@link DynamicScheme} so that it can be used by {@link StyleFromScheme} and {@link genCSS}.
 * @param scheme The theme generated by material-color-utils.
 * */

export const serializeScheme = (scheme: DynamicScheme) => {
  const out: Record<string, number> = {};
  for (const color of colors) {
    out[color] = MaterialDynamicColors[color].getArgb(scheme);
  }
  return out as SerializedScheme;
};
