name: Check TS

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: PNPM
        with:
          version: latest
          run_install: false
      - name: Run install
        run: pnpm install
      - name: Run check
        run: pnpm run check
