name: Check TS

on:
  push:
    branches: ["main"]

  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run install
        run: pnpm install
      - name: Run check
        run: pnpm run check
